export const desktopIconsData = [
  {
    id: 1,
    className: "icon-desktop",
    iconUrl: "/js.png",
    top: "92px",
    right: "400px",
  },
  {
    id: 2,
    className: "icon-desktop",
    iconUrl: "/mongodb.png",
    top: "0",
    left: "300px",
    width: "40px",
    height: "40px",
  },
  {
    id: 3,
    className: "icon-desktop",
    iconUrl: "/react.png",
    top: "150px",
    left: "50px",
  },
  {
    id: 4,
    className: "icon-desktop",
    iconUrl: "/rest.png",
    top: "300px",
    left: "230px",
  },
  {
    id: 5,
    className: "icon-desktop",
    iconUrl: "/styled.png",
    top: "250px",
    right: "100px",
  },
  {
    id: 6,
    className: "icon-desktop",
    iconUrl: "/tailwind.png",
    top: "50px",
    right: "112px",
    left: "none",
  },
  {
    id: 7,
    className: "icon-desktop",
    iconUrl: "/figma.png",
    width: "40px",
    height: "40px",
    top: "30px",
    left: "150px",
  },
  {
    id: 8,
    className: "icon-desktop",
    iconUrl: "/next-js.svg",
    top: "20px",
    left: "none",
    width: "50px",
    height: "50px",
  },
  {
    id: 9,
    className: "icon-desktop",
    iconUrl: "/html.png",
    left: "none",
    top: "-36px",
    right: "259px",
  },
];

export const MobileIconsData = [
  {
    id: 1,
    className: "icon-desktop",
    iconUrl: "/js.png",
    top: "92px",
    right: "200px",
  },
  {
    id: 2,
    className: "icon-desktop",
    iconUrl: "/mongodb.png",
    top: "0",
    left: "300px",
    width: "40px",
    height: "40px",
  },
  {
    id: 3,
    className: "icon-desktop",
    iconUrl: "/react.png",
    top: "100px",
    left: "30px",
  },
  {
    id: 4,
    className: "icon-desktop",
    iconUrl: "/rest.png",
    top: "100px",
    left: "250px",
  },
  {
    id: 5,
    className: "icon-desktop",
    iconUrl: "/styled.png",
    top: "-30px",
    right: "80px",
  },
  {
    id: 6,
    className: "icon-desktop",
    iconUrl: "/tailwind.png",
    top: "50px",
    right: "112px",
    left: "none",
  },
  {
    id: 7,
    className: "icon-desktop",
    iconUrl: "/figma.png",
    width: "40px",
    height: "40px",
    top: "-30px",
    left: "150px",
  },
  {
    id: 8,
    className: "icon-desktop",
    iconUrl: "/next-js.svg",
    top: "20px",
    left: "30px",
    width: "50px",
    height: "50px",
  },
  {
    id: 9,
    className: "icon-desktop",
    iconUrl: "/html.png",
    left: "none",
    top: "-36px",
    right: "259px",
  },
];
