export const desktopIconsData = [
  {
    id: 1,
    className: "icon-desktop",
    iconUrl: "/js.png",
    top: "10%",
    right: "40%",
  },
  {
    id: 2,
    className: "icon-desktop",
    iconUrl: "/mongodb.png",
    top: "0",
    left: "30%",
    width: "40px",
    height: "40px",
  },
  {
    id: 3,
    className: "icon-desktop",
    iconUrl: "/react.png",
    top: "15%",
    left: "40%",
  },
  {
    id: 4,
    className: "icon-desktop",
    iconUrl: "/rest.png",
    top: "25%",
    left: "10%",
  },
  {
    id: 5,
    className: "icon-desktop",
    iconUrl: "/styled.png",
    top: "25%",
    right: "10%",
  },
  {
    id: 6,
    className: "icon-desktop",
    iconUrl: "/tailwind.png",
    top: "50px",
    right: "20%",
    left: "none",
  },
  {
    id: 7,
    className: "icon-desktop",
    iconUrl: "/figma.png",
    width: "40px",
    height: "40px",
    top: "15%",
    left: "20%",
  },
  {
    id: 8,
    className: "icon-desktop",
    iconUrl: "/next-js.svg",
    top: "10%",
    left: "25%",
    width: "50px",
    height: "50px",
  },
  {
    id: 9,
    className: "icon-desktop",
    iconUrl: "/html.png",
    left: "none",
    top: "-36px",
    right: "259px",
  },
  {
    id: 10,
    className: "icon-desktop",
    iconUrl: "/typescript.png",
    left: "none",
    top: "30%",
    right: "10%",
    width: "50px",
    height: "50px",
  },
];

export const MobileIconsData = [
  {
    id: 1,
    className: "icon-desktop",
    iconUrl: "/js.png",
    top: "5%",
    right: "10%",
  },
  {
    id: 2,
    className: "icon-desktop",
    iconUrl: "/mongodb.png",
    top: "0",
    left: "30%",
    width: "40px",
    height: "40px",
  },
  {
    id: 3,
    className: "icon-desktop",
    iconUrl: "/react.png",
    top: "10%",
    left: "40%",
  },
  {
    id: 4,
    className: "icon-desktop",
    iconUrl: "/rest.png",
    top: "40%",
    left: "10%",
  },
  {
    id: 5,
    className: "icon-desktop",
    iconUrl: "/styled.png",
    top: "40%",
    right: "10%",
  },
  {
    id: 6,
    className: "icon-desktop",
    iconUrl: "/tailwind.png",
    top: "50px",
    right: "20%",
    left: "none",
  },
  {
    id: 7,
    className: "icon-desktop",
    iconUrl: "/figma.png",
    width: "40px",
    height: "40px",
    top: "20%",
    left: "25%",
  },
  {
    id: 8,
    className: "icon-desktop",
    iconUrl: "/next-js.svg",
    top: "1%",
    left: "15%",
    width: "50px",
    height: "50px",
  },
  {
    id: 9,
    className: "icon-desktop",
    iconUrl: "/html.png",
    left: "none",
    top: "-10%",
    right: "25%",
  },
  {
    id: 10,
    className: "icon-desktop",
    iconUrl: "/typescript.png",
    left: "none",
    top: "20%",
    right: "30%",
    width: "50px",
    height: "50px",
  },
];
